<div id="all">
  <div id="content_wrap">
    <section id="bar_1">
      <ul id="breadcrumb">
        <li>Você está em:</li>
        <li class="pagina">Sobre</li>
      </ul>
    </section>
    <div>
      <br/>

      <span class="ftr">
        <br/>
        <b>SOBRE</b>
        <br/>
        SEMANA DE INICIACAO CIENTIFICA

        <hr>
        <br/>
        <span class="left">Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker.</span>
      </span>

    </div>
  </div>
</div>