<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
  <head>
      <?php include "./includes/head.php"; ?>
  </head>
  <body>

    <div id="all">
        <?php include "./includes/header.php"; ?>
      <div id="content_wrap">
        <section id="bar_1">
          <ul id="breadcrumb">
            <li>Você está em:</li>
            <li class="pagina">Sobre</li>
          </ul>
        </section>
        <div>
          <br/>


          <span class="ftr">
            <br/>
            <b>SOBRE</b>
            <br/>
            SEMANA DE INICIACAO CIENTIFICA

            <hr>
              <br/>

              <?php
              require 'controller/postagem.class.php';
              $postagem = new postagem();
              $allpostagem = $postagem->ultimas_postagem();
              foreach ($allpostagem as $postagem) {
                print_r($postagem->get('postagemTitulo'));
              }
              ?>
              <span class="left">Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker.</span>
          </span>

        </div>
      </div>
      <?php include "./includes/footer.php"; ?>

    </div>
  </body>
</html>
