<div id="all">
    <div id="content_wrap">
        <section id="bar_1">
            <ul id="breadcrumb">
                <li>Você está em:</li>
                <li class="pagina">Sobre</li>
            </ul>
        </section>
        <div>
            <br/>

            <span class="ftr">
                <br/>
                <b>SEMANA DE INICIACAO CIENTIFICA</b>
                <hr>
                <br/>
                <span class="left">

                    <p>
                        O evento constará de palestras de interesse dos diversos cursos, bem como apresentação de pôsteres das pesquisas e trabalhos desenvolvidos pelos alunos e professores da UNIANDRADE.
                    </p>
                    <b>
                        Inscrições
                    </b>
                    <p>
                        Do dia 20 de outubro a 14 de novembro.

                        Valor de R$15,00 (quinze reais).

                        O aluno deve realizar a inscrição pelo site da UNIANDRADE. Neste momento, será gerado boleto para pagamento, podendo ser quitado na Central ou agencias bancárias. Após o pagamento, o aluno deve se dirigir até a Central para receber uma ficha de controle de participação, a qual deverá ser carimbada durante a realização das palestras (que valerá como registro de presença) e após a apresentação do pôster. Essa ficha, posteriormente, deverá ser entregue ao coordenador de curso no momento da retirada do certificado.

                    </p>
                </span>
            </span>
            <b>
        </div>
    </div>
</div>