<?php foreach ($this->postagens as $posts) { ?>
    <div class="projetos">
        <i> <b>Autor: </b> Gilson Gonçalves Junior</i><br/>
        <i> <b>Titulo: </b> <?php echo  utf8_encode($posts['equipePostagemTitulo']);?></i><br/>
        <i> <b>Data:</b> <?php echo  utf8_encode($posts['equipePostagemData']);?> </i>
        <div class="centralizar">
            <div>   
                <img src="http://placehold.it/330x220">
                <img src="http://placehold.it/330x220">
                <img src="http://placehold.it/330x220">
            </div>
            <p>
                <?php
                echo utf8_encode($posts['equipePostagemDescricao']);
                ?>
            </p>
            <a href="#" class="btn btn-danger">
                Ver Postagem
            </a>
        </div>
        <hr>
    </div>
<?php } ?>