<?php if (count($this->messages) == 1) { ?>
    <?php foreach ($this->messages as $msg) { ?>
        <div class="alert alert-primary alert-white rounded">
            <div class="icon"><i class="fa fa-check"></i></div>
            <?php echo $msg; ?>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
    <?php } ?>
<?php } ?>
<div class="row">
    <div class="col-md-12">
        <div class="block-flat">
            <div class="header">
                <h4><i class="fa fa-user"></i> Alterar dados</h4>
            </div>
            <div class="content">
                <form enctype="multipart/form-data" action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuarioAluno', 'action' => 'save'), null,true);?>" class="form-horizontal group-border-dashed" style="border-radius: 0px;" method="post">
                    
                    <input type="hidden" name="usuarioId" value="<?php echo $this->usuario->usuarioId ?>"/>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Login</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" name="usuarioLogin" value="<?php echo $this->usuario->usuarioLogin ;?>">
                         </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Senha</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control" name="usuarioSenha" value="" placeholder="Digite a sua senha aqui"/>
                        </div>
                        <div class="col-sm-3">
                            <input type="text" class="form-control" name="confirmaSenha" placeholder="Confirme sua senha aqui" value=""/>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-3 control-label"></label>
                        <div class="col-sm-6">
                            <input type="submit" class="btn btn-primary" value="Confirmar"/>
                        </div>
                    </div>                    
                </form>
            </div>
        </div>
    </div>
</div>