<div class="row">
    <div class="col-md-12">
        <div class="block-flat">
            <div class="header">
                <h4><i class="fa fa-user"></i> Alterar dados</h4>
            </div>
            <div class="content">
                <form enctype="multipart/form-data" action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'curso', 'action' => 'save'), null, true); ?>" class="form-horizontal group-border-dashed" style="border-radius: 0px;" method="post">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Nome</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" name="cursoNome" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Senha</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" name="cursoNome" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Login</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" name="cursoNome" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label"></label>
                        <div class="col-sm-6">
                            <input type="submit" class="btn btn-primary" value="Confirmar"/>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>