<div id="content">
	<div id="titulo" style="width: 800px;margin:auto; text-align: center;">

		<div>
			<h2>Desenvolvedores</h2>
		</div>
		<div id="foto">
			<div class="size50 pos10">
				<a href="imagens/piterson.jpg" rel="shadowbox[mixed]"><img src="imagens/piterson.jpg" width="240" height="240"></a>
			</div>
		</div>
		<div id="informacoes">
			<h5>
				Desenvolvedor: Piterson Costa
			</h5>
		</div>

		<hr>

		<br/>
		<div class="size50 pos10">
			<a href="imagens/julian.jpg" rel="shadowbox[mixed]"><img src="imagens/julian.jpg" width="240" height="240"></a>
		</div>
		<div id="informacoes">
			<h5>
				Desenvolvedor: Julian Ribeiro
			</h5>
		</div>

		<hr>
		
		<br/>
		<div class="size50 pos10">
			<a href="imagens/gilson.png" rel="shadowbox[mixed]"><img src="imagens/gilson.png" width="240" height="240"></a>
		</div>
		<div id="informacoes">
			<h5>
				Desenvolvedor: Gilson Goncalves Jr.
			</h5>
		</div>
		<br/>
	</div>
	<hr>
	<br/>
</div>
