<div class="row">
  <div class="col-md-12">
    <div class="block-flat">
      <div class="header">
        <h3><?php echo $this->formActionName ?> menu</h3>
      </div>
      <div class="content">
       <div class="form-horizontal group-border-dashed" style="border-radius: 0px;">
        <div class="form-group">
          <label class="col-sm-3 control-label">Título</label>
          <div class="col-sm-6">
            <p class="form-control-static"><?php echo $this->menu['menuTitulo'] ?></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">MVC</label>
          <div class="col-sm-3">
            <p class="form-control-static"><?php echo $this->menu['menuController'] . "@" . $this->menu['menuAction'] ?></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Ordem</label>
          <div class="col-sm-6">
            <p class="form-control-static"><?php echo $this->menu['menuOrdem'] ?></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Ícone</label>
          <div class="col-sm-6">
            <p class="form-control-static"><?php echo$this->menu['menuIcone'] ?></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Superior</label>
          <div class="col-sm-6">
            <p class="form-control-static"><?php echo $this->menu['menuSuperior'] == 0 ? "" : $this->menu['menuSuperior']['nome'] ?></p>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-9 col-sm-offset-3">
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'menu', 'action' => 'form')); ?>" class="btn btn-primary">Editar</a>
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'menu', 'action' => 'index'), null, true); ?>" class="btn btn-default">Voltar</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>