<?php
foreach ($this->curso as $cursos) {
    if (!empty($cursos['cursoBanner'])) {
        $banners['nome'] = $cursos['cursoBanner'];
        $cursos['cursoNome'] = $cursos['cursoNome'];
    }
}
?>

<?php foreach ($banners as $banner) { ?>
    <div id="cursos">
        <div class="centralizar">
            <img src="<?php echo 'imagens/'.$banner; ?>" style="width: 800px; height: 180px;"/>
        </div>
        <div id="curso-nome">
            <i><strong>Curso:</strong> Ciência da Computação<br/></i>
        </div>
        <hr>
    </div>
<?php } ?>