<section id="galery">

    <div id="overlay"></div>

    <div class="size150 pos9">
        <?php 
        $x = 1;
        foreach ($this->caminhos as $imagem) { ?>

        <?php if($x < 11){ ?>
        <a href="imagens/<?php echo $imagem['equipeUploadCaminho'];?>" rel="shadowbox[mixed]"><img src="imagens/<?php echo $imagem['equipeUploadCaminho'];?>" /></a> 
        <?php $x++ ;} ?>
        
        <?php }?>
    </div>
</section>
<div style="text-align: center; width: 980px; margin: auto;">
    <h3>
        Trabalhos recentes
    </h3>   
  </div>
<div class="postagens-recentes">
    <?php
    $x = 0;
    foreach ($this->postagens as $posts) { ?>

    <?php if($x > 2){
        break;
    } 
    $x++;

    ?>
    <div class="postagens" style="text-align: center;">
        <h4>
            <?php echo utf8_encode($posts['equipePostagemTitulo']); ?>
        </h4>

        <?php
        echo substr($posts['equipePostagemDescricao'], 1, 330) . ' [...]';
        ?>

        <div class="continuar-lendo" style="text-align: center;">
            <br/>
            <form>
                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'projeto', 'action' => 'post', 'id' => $posts['equipePostagemId'])); ?>" class="btn btn-danger">
                    Ver Postagem
                </a>    
            </form>
        </div>
    </div>
    <?php
    
}
?>  
</div>
<br/>




