<section id="bar_1">
  <ul id="breadcrumb">
    <li>Você está em:</li>
    <li class="pagina">Home</li>
  </ul>

</section>
<div class="clear"></div>

<section id="galery">
  <div id="overlay"></div>
  <div class="size100 pos1">
    <a href="assets/site/images/galeria/1.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/1.jpg" /></a>
  </div>
  <div class="size50 pos2">
    <a href="assets/site/images/galeria/2.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/2.jpg" /></a>
  </div>
  <div class="size50 pos3">
    <a href="assets/site/images/galeria/3.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/3.jpg" /></a>
  </div>
  <div class="size100 pos4">
    <a href="assets/site/images/galeria/4.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/4.jpg" /></a>
  </div>
  <div class="size150 pos5">
    <a href="assets/site/images/galeria/5.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/5.jpg" /></a>
  </div>
  <div class="size50 pos6">
    <a href="assets/site/images/galeria/6.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/6.jpg" /></a>
  </div>
  <div class="size50 pos7">
    <a href="assets/site/images/galeria/7.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/7.jpg" /></a>
  </div>
  <div class="size50 pos8">
    <a href="assets/site/images/galeria/8.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/8.jpg" /></a>
  </div>
  <div class="size150 pos9">
    <a href="assets/site/images/galeria/9.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/9.jpg" /></a>
  </div>
  <div class="size50 pos10">
    <a href="assets/site/images/galeria/10.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/10.jpg" /></a>
  </div>
  <div class="size200 pos11">
    <a href="assets/site/images/galeria/11.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/11.jpg" /></a>
  </div>
  <div class="size200 pos12">
    <a href="assets/site/images/galeria/12.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/12.jpg" /></a>
  </div>
  <div class="size50 pos13">
    <a href="assets/site/images/galeria/13.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/13.jpg" /></a>
  </div>
  <div class="size50 pos14">
    <a href="assets/site/images/galeria/14.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/14.jpg" /></a>
  </div>
  <div class="size50 pos15">
    <a href="assets/site/images/galeria/15.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/15.jpg" /></a>
  </div>
  <div class="size50 pos16">
    <a href="assets/site/images/galeria/16.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/16.jpg" /></a>
  </div>

  <div class="size100 pos17">
    <a href="assets/site/images/galeria/17.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/17.jpg" /></a>
  </div>

  <div class="size100 pos18">
    <a href="assets/site/images/galeria/15.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/15.jpg" /></a>
  </div>
  <div class="size50 pos19">
    <a href="assets/site/images/galeria/16.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/16.jpg" /></a>
  </div>
  <div class="size50 pos20">
    <a href="assets/site/images/galeria/17.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/17.jpg" /></a>
  </div>             
  <div class="size100 pos21">
    <a href="assets/site/images/galeria/1.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/1.jpg" /></a>
  </div>
  <div class="size150 pos22">
    <a href="assets/site/images/galeria/2.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/2.jpg" /></a>
  </div>
  <div class="size50 pos23">
    <a href="assets/site/images/galeria/3.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/3.jpg" /></a>
  </div>
  <div class="size50 pos24">
    <a href="assets/site/images/galeria/4.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/4.jpg" /></a>
  </div>
  <div class="size50 pos25">
    <a href="assets/site/images/galeria/5.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/5.jpg" /></a>
  </div>
  <div class="size150 pos26">
    <a href="assets/site/images/galeria/6.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/6.jpg" /></a>
  </div>
  <div class="size50 pos27">
    <a href="assets/site/images/galeria/7.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/7.jpg" /></a>
  </div>
  <div class="size200 pos28">
    <a href="assets/site/images/galeria/8.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/8.jpg" /></a>
  </div>
  <div class="size200 pos29">
    <a href="assets/site/images/galeria/9.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/9.jpg" /></a>
  </div>
  <div class="size50 pos30">
    <a href="assets/site/images/galeria/10.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/10.jpg" /></a>
  </div>
  <div class="size50 pos31">
    <a href="assets/site/images/galeria/11.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/11.jpg" /></a>
  </div>
  <div class="size50 pos32">
    <a href="assets/site/images/galeria/12.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/12.jpg" /></a>
  </div>
  <div class="size50 pos33">
    <a href="assets/site/images/galeria/13.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/13.jpg" /></a>
  </div>
  <div class="size100 pos34">
    <a href="assets/site/images/galeria/14.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/14.jpg" /></a>
  </div>
</section>
<div class="clear"></div>

<section id="updates">
  <aside id="post">
    <h3 class="semibold">Ultimas Atualizações</h3>
    <p class="post">
      <span class="post-title bold"> Aqui vai o titulo da postagem </span> - Postado por fulano
      <br/>
      Lorem Ipsum simplesmente uma simulação de texto da
      industria tipografica e de impressos, e vem sendo utilizado
      desde o suculo XVI, quando um impressor desconhecido [...]
      <span class="ftr">
        <span class="left">20/10/2014 hs 02h09</span>
        <a  href="?pagina=projetos&acao=postagem_id&id=<?= $id; ?>" class="btn right">Continuar lendo<span class="seta"></span></a>
      </span>
    </p>
    <p class="post">
      <span class="post-title bold"> Aqui vai o titulo da postagem </span> - Postado por fulano
      <br/>
      Lorem Ipsum simplesmente uma simulação de texto da
      industria tipografica e de impressos, e vem sendo utilizado
      desde o suculo XVI, quando um impressor desconhecido [...]
      <span class="ftr">
        <span class="left">20/10/2014 hs 02h09</span>
        <a  href="?pagina=projetos&acao=postagem_id&id=<?= $id; ?>" class="btn right">Continuar lendo<span class="seta"></span></a>
      </span>
    </p>
  </aside>
  <aside id="comment">
    <h3 class="semibold">Ultimos Comentarios</h3>
    <p class="comment">
      <br/>
      Lorem Ipsum simplesmente uma simulação de texto da
      industria tipografica e de impressos, e vem sendo utilizado
      desde o suculo XVI, quando um impressor desconhecido [...]
      <span class="ftr">
        <a href="#" class="btn right ver_postagem">Ver postagem<span class="seta"></span></a>
      </span>
    </p>
    <p class="comment">
      <br/>
      Lorem Ipsum simplesmente uma simulação de texto da
      industria tipografica e de impressos, e vem sendo utilizado
      desde o suculo XVI, quando um impressor desconhecido [...]
      <span class="ftr">
        <a href="#" class="btn right ver_postagem">Ver postagem<span class="seta"></span></a>
      </span>
    </p>    
  </aside>
  <div class="clear"></div> 
  <div class="clear"></div>
</section>
<br/>
<br/>
