<section id="galery">
    <div id="overlay"></div>
    <div class="size100 pos1">
        <a href="assets/site/images/galeria/1.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/1.jpg" /></a>
    </div>
    <div class="size50 pos2">
        <a href="assets/site/images/galeria/2.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/2.jpg" /></a>
    </div>
    <div class="size50 pos3">
        <a href="assets/site/images/galeria/3.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/3.jpg" /></a>
    </div>
    <div class="size100 pos4">
        <a href="assets/site/images/galeria/4.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/4.jpg" /></a>
    </div>
    <div class="size150 pos5">
        <a href="assets/site/images/galeria/5.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/5.jpg" /></a>
    </div>
    <div class="size50 pos6">
        <a href="assets/site/images/galeria/6.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/6.jpg" /></a>
    </div>
    <div class="size50 pos7">
        <a href="assets/site/images/galeria/7.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/7.jpg" /></a>
    </div>
    <div class="size50 pos8">
        <a href="assets/site/images/galeria/8.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/8.jpg" /></a>
    </div>
    <div class="size150 pos9">
        <a href="assets/site/images/galeria/9.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/9.jpg" /></a>
    </div>
    <div class="size50 pos10">
        <a href="assets/site/images/galeria/10.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/10.jpg" /></a>
    </div>
    <div class="size200 pos11">
        <a href="assets/site/images/galeria/11.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/11.jpg" /></a>
    </div>
    <div class="size200 pos12">
        <a href="assets/site/images/galeria/12.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/12.jpg" /></a>
    </div>
    <div class="size50 pos13">
        <a href="assets/site/images/galeria/13.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/13.jpg" /></a>
    </div>
    <div class="size50 pos14">
        <a href="assets/site/images/galeria/14.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/14.jpg" /></a>
    </div>
    <div class="size50 pos15">
        <a href="assets/site/images/galeria/15.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/15.jpg" /></a>
    </div>
    <div class="size50 pos16">
        <a href="assets/site/images/galeria/16.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/16.jpg" /></a>
    </div>

    <div class="size100 pos17">
        <a href="assets/site/images/galeria/17.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/17.jpg" /></a>
    </div>

    <div class="size100 pos18">
        <a href="assets/site/images/galeria/15.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/15.jpg" /></a>
    </div>
    <div class="size50 pos19">
        <a href="assets/site/images/galeria/16.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/16.jpg" /></a>
    </div>
    <div class="size50 pos20">
        <a href="assets/site/images/galeria/17.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/17.jpg" /></a>
    </div>             
    <div class="size100 pos21">
        <a href="assets/site/images/galeria/1.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/1.jpg" /></a>
    </div>
    <div class="size150 pos22">
        <a href="assets/site/images/galeria/2.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/2.jpg" /></a>
    </div>
    <div class="size50 pos23">
        <a href="assets/site/images/galeria/3.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/3.jpg" /></a>
    </div>
    <div class="size50 pos24">
        <a href="assets/site/images/galeria/4.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/4.jpg" /></a>
    </div>
    <div class="size50 pos25">
        <a href="assets/site/images/galeria/5.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/5.jpg" /></a>
    </div>
    <div class="size150 pos26">
        <a href="assets/site/images/galeria/6.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/6.jpg" /></a>
    </div>
    <div class="size50 pos27">
        <a href="assets/site/images/galeria/7.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/7.jpg" /></a>
    </div>
    <div class="size200 pos28">
        <a href="assets/site/images/galeria/8.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/8.jpg" /></a>
    </div>
    <div class="size200 pos29">
        <a href="assets/site/images/galeria/9.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/9.jpg" /></a>
    </div>
    <div class="size50 pos30">
        <a href="assets/site/images/galeria/10.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/10.jpg" /></a>
    </div>
    <div class="size50 pos31">
        <a href="assets/site/images/galeria/11.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/11.jpg" /></a>
    </div>
    <div class="size50 pos32">
        <a href="assets/site/images/galeria/12.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/12.jpg" /></a>
    </div>
    <div class="size50 pos33">
        <a href="assets/site/images/galeria/13.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/13.jpg" /></a>
    </div>
    <div class="size100 pos34">
        <a href="assets/site/images/galeria/14.jpg" rel="shadowbox[mixed]"><img src="assets/site/images/galeria/14.jpg" /></a>
    </div>
</section>

<div class="postagens-recentes">
    <div>
        <h3 class="centralizar">
            Postagens Recentes
        </h3>
    </div>
    <div class="postagens" style="text-align: center;">
        <h4>
            Titulo da Postagem 
        </h4>
        Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, 
        e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. 
        Lorem Ipsum sobreviveu de tipos e os embaralhou para fazer um livro de modelos de tipos [...]
        <div class="continuar-lendo" style="text-align: center;">
            <br/>
            <form>
                <a class="btn btn-danger">
                    ler mais
                </a>
            </form>
        </div>
    </div>
    <div class="postagens" style="text-align: center;">
        <h4>
            Titulo da Postagem 
        </h4>
        Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, 
        e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. 
        Lorem Ipsum sobreviveu de tipos e os embaralhou para fazer um livro de modelos de tipos [...]
        <div class="continuar-lendo" style="text-align: center;">
            <br/>
            <form>
                <a class="btn btn-danger">
                    ler mais
                </a>
            </form>
        </div>
    </div>
    <div class="postagens" style="text-align: center;">
        <h4>
            Titulo da Postagem 
        </h4>
        Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, 
        e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. 
        Lorem Ipsum sobreviveu de tipos e os embaralhou para fazer um livro de modelos de tipos [...]
        <div class="continuar-lendo" style="text-align: center;">
            <br/>
            <form>
                <a class="btn btn-danger">
                    ler mais
                </a>
            </form>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

<br/>
