<?php if (count($this->messages) == 1) { ?>
    <?php foreach ($this->messages as $msg) { ?>
        <div class="alert alert-primary alert-white rounded">
            <div class="icon"><i class="fa fa-check"></i></div>
            <?php echo $msg; ?>
        </div>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <?php } ?>
<?php } ?>

<div class="block-flat">
    <div class="header">              
        <h4><i class="fa fa-graduation-cap"></i> Cadastro de Cursos</h4>
    </div>
    <div class="content">
        <div class="container-fluid text-center">
            <a href="<?php echo $this->url(array('action' => 'form')) ?>" class="btn btn-trans btn-primary"><i class="fa fa-plus"></i>&nbsp;&nbsp;Novo curso</a>
        </div>
        <div class="table table-responsive">
            <?php
            if (empty($this->curso)) {
                echo 'não existem cursos cadastrados nesse sistema.';
            } else {
                ?>
                <table class="no-border hover">
                    <thead class="no-border">
                        <tr>
                            <th class="text-left">Cursos</th>
                            <th class="text-right"></th>
                        </tr>
                    </thead>

                    <tbody class="no-border-y"> 
                        <?php foreach ($this->curso as $cursos) { ?>
                            <tr>
                                <td class="text-left">
                                    <?php echo utf8_encode($cursos['cursoNome']); ?>
                                </td>
                                <td class="text-right">
                                    <a class="btn btn-primary" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'curso', 'action' => 'view', 'id' => $cursos['cursoId']), null, true); ?>">
                                        <i class="fa fa-search">
                                        </i>
                                    </a>

                                    <button data-toggle="modal"  data-target="#mod-error" type="button" class="btn btn-danger btn-flat"><i class="fa fa-trash"></i></button>

                                    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'curso', 'action' => 'form', 'id' => $cursos['cursoId'])); ?>" class="btn btn-success">
                                        <i class="fa fa-edit">    
                                        </i>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            <?php } ?>
        </div>            
    </div>
</div>
<div class="modal fade" id="mod-error" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <div class="i-circle danger"><i class="fa fa-times"></i></div>
                    <h4>Atenção!</h4>
                    <p>Deseja realmente excluir esse curso?</p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Cancel</button>
                <a class="btn btn-default btn-flat" href="<?php
                echo $this->
                        url(array('module' => 'admin', 'controller' => 'curso', 'action' => 'drop', 'id' => $cursos['cursoId']), null, true);
                ?>">
                    Confirmar
                </a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->