<div class="row">
  <div class="col-md-12">
    <div class="block-flat">
      <div class="header">
        <h4><?php echo $this->formActionName ?> <i class="fa fa-graduation-cap"> <?php echo utf8_encode($this->curso['cursoNome']);?></i></h4>
      </div>
      <div class="content">
       <div class="form-horizontal group-border-dashed" style="border-radius: 0px;">
        <div class="form-group">
          <label class="col-sm-1 control-label">Banner</label>
          <div class="col-sm-6">
            <p class="form-control-static">
              <img width="800" height="180" src="<?php echo empty($this->curso['cursoBanner']) ? 'http://placehold.it/800x180' : 'imagens/' . $this->curso['cursoBanner']; ?>"/>
            </p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 control-label"></label>
          <div class="col-sm-6">
            <p class="form-control-static">
              <a  class="btn btn-danger" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'curso', 'action' => 'index'),null,true);?>">
            Voltar 
          </a>
          <a  class="btn btn-primary" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'curso', 'action' => 'form', 'id' => $this->curso['cursoId']),null,true);?>">
            Editar 
          </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




