<section id="bar_1">
  <ul id="breadcrumb">
    <li>Você está em:</li>
    <li class="pagina">Projeto</li>
  </ul>
</section>
<div class="clear"></div>
<div>
  <section id="updates">              
    <div style="width: 700px;">
      <br/>
      <span class="ftr">
        <br/>
        <h3 style="margin-top: 30px;"><b>Lorem ipsum Nisi ex consectetur sunt non laboris </b></h3>
        <hr>
        <div id="blog_img">
          <a href="http://placehold.it/350x150" rel="shadowbox[mixed]"><img style="width: 421px;height: 316px" src=" http://placehold.it/421x316" /></a>

          <div id="blog_texto">
            <span class="left" style="text-align: justify;">

              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur [...]
            </span>
          </div>
          <div>
            <span class="ftr">
              <a href="#" class="btn right ver_postagem">Ver postagem<span class="seta"></span></a>
            </span>
          </div>
        </div>
        <div>
          <br/><br/>
          Postado por: Gilson Gonçalves Junior
          <br/>
          Data: 22/10/2014
        </div>
      </span>
    </div>
  </section>

  <section id="updates">              
    <div style="width: 700px;">
      <br/>
      <span class="ftr">
        <br/>
        <h3 style="margin-top: 30px;"><b>Lorem ipsum Nisi ex consectetur sunt non laboris </b></h3>

        <hr>
        <div id="blog_img">
          <a href="images/galeria/16.jpg" rel="shadowbox[mixed]"><img style="width: 421px;height: 316px" src="http://placehold.it/421x316" /></a>

          <div id="blog_texto">
            <span class="left" style="text-align: justify;">

              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur [...]
            </span>
          </div>
          <div>
            <span class="ftr">
              <a href="#" class="btn right ver_postagem">Ver postagem<span class="seta"></span></a>
            </span>
          </div>
        </div>
        <div>
          <br/><br/>
          Postado por: Gilson Gonçalves Junior
          <br/>
          Data: 22/10/2014
        </div>
      </span>
    </div>
  </section>

  <section id="updates">              
    <div style="width: 700px;">
      <br/>
      <span class="ftr">
        <br/>
        <h3 style="margin-top: 30px;"><b>Lorem ipsum Nisi ex consectetur sunt non laboris </b></h3>

        <hr>
        <div id="blog_img">
          <a href="assets/site/images/galeria/16.jpg" rel="shadowbox[mixed]"><img style="width: 421px;height: 316px" src="http://placehold.it/421x316" /></a>

          <div id="blog_texto">
            <span class="left" style="text-align: justify;">

              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur sunt non laboris magna elit ullamco amet cupidatat Ut laborum aute cupidatat sit ut eu elit mollit laboris ea est cillum occaecat culpa officia eu id.
              Lorem ipsum Nisi ex consectetur 
            </span>
          </div>
          <div>
            <span class="ftr">
              <a href="#" class="btn right ver_postagem">Ver postagem<span class="seta"></span></a>
            </span>
          </div>
        </div>
        <div>
          <br/><br/>
          Postado por: Gilson Gonçalves Junior
          <br/>
          Data: 22/10/2014
        </div>
      </span>
    </div>
  </section>
</div>
<div class="clear"></div>

<br/>
<br/>


