<div class="block-flat">
    <div class="content">
        <div class="table table-responsive">
            <table class="no-border hover">
                <thead class="no-border">
                <caption>
                    <h4>
                        Veja os trabalhos das equipes que você está cadastrado!
                    </h4>
                </caption>
                    <tr>
                        <th class="text-left">Minhas Equipes!</th>
                        <th class="text-right"></th>
                    </tr>
                </thead>

                <tbody class="no-border-y"> 
                    <?php foreach ($this->equipes as $value) { ?>
                        <tr>
                            <td class="text-left">
                                <?php echo $value['equipeNome']; ?>
                            </td>
                            <td class="text-right">
                                <a class="btn btn-primary" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'equipePostagem', 'action' => 'view', 'id' => $value['equipeId']),null,true);?>">
                                    <i class="fa fa-search">
                                    </i>
                                    Integrantes 
                                </a>

                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'equipePostagem', 'action' => 'listar-projeto', 'id' => $value['equipeId']), null, true); ?>" class="btn btn-success">
                                    <i class="fa fa-suitcase">    
                                    </i>
                                    Ver Projetos
                                </a>

                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'equipePostagem', 'action' => 'form', 'id' => $value['equipeId']), null, true); ?>" class="btn btn-success">
                                    <i class="fa fa-suitcase">    
                                    </i>
                                    Criar projetos
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>            
    </div>
</div>