<?php
$ids = array();
if(!$this->id == null){

foreach ($this->integrantesEquipeFiltro as $integrantes) {
$ids[] = $integrantes['usuarioEquipeUsuarioId'];
}
}
?>
<div class="row">
    <div class="col-md-12">
        <div class="block-flat">
            <div class="header">
                <h4><i class="fa fa-suitcase"></i> Equipes </h4>
            </div>
            <div class="content">
                <form method="post" action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'equipe', 'action' => 'save'), null, true); ?>" class="form-horizontal group-border-dashed" style="border-radius: 0px;">

                    <?php if ($this->id) { ?>
                        <input type="hidden" name="equipeId" value="<?php echo $this->id; ?>">
                    <?php } ?>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Nome</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" name="equipeNome" value="<?php echo!empty($this->equipeFiltro['equipeNome']) ? $this->equipeFiltro['equipeNome'] : '' ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Integrantes</label>
                        <div class="col-sm-6">
                            <?php
                            
                            foreach ($this->usuarioAll as $usuarios) { ?>
                                <?php $idsUsuarioAll = $usuarios['usuarioId']; ?>
                                <?php if (in_array($idsUsuarioAll, $ids)) { ?>
                                    <input name="integrantes[]" type="checkbox" checked value="<?php echo $usuarios['usuarioId'] ?>"> <?php echo utf8_encode($usuarios['usuarioNome']); ?><br/>
                                <?php } else { ?>
                                    <input name="integrantes[]" type="checkbox" value="<?php echo $usuarios['usuarioId'] ?>"> <?php echo utf8_encode($usuarios['usuarioNome']); ?><br/>
                                <?php } ?>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label"></label>
                        <div class="col-sm-6">
                            <input type="submit" class="btn btn-primary" value="Confirmar"/>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>