<?php
$ids = array();
$idsFiltrados = array();
if ($this->id) {
    foreach ($this->usuario as $id) {
        $ids[] = $id['usuarioId'];
    }
    
    foreach ($this->usuarioEquipes as $idFiltrado) {
        $idsFiltrados[] = $idFiltrado['usuarioId'];
    }
    
    echo '<pre>';
    print_r($idsFiltrados);
    echo '</pre>';
}
?>
<div class="row">
    <div class="col-md-12">
        <div class="block-flat">
            <div class="header">
                <h4><i class="fa fa-suitcase"></i> Equipes </h4>
            </div>
            <div class="content">
                <form method="post" action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'equipe', 'action' => 'save'), null, true); ?>" class="form-horizontal group-border-dashed" style="border-radius: 0px;">

                    <?php if ($this->id) { ?>
                        <input type="hidden" name="equipeId" value="<?php echo $this->id; ?>">
                    <?php } ?>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Nome</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" name="equipeNome" value="<?php echo empty($this->equipeFiltro['equipeNome']) ? '' : utf8_encode($this->equipeFiltro['equipeNome']) ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Nome</label>
                        <div class="col-sm-6">
                            <?php if ($this->id == null) { ?>
                                <?php foreach ($this->usuario as $usuarios) { ?>
                                    <input name="integrantes[]" type="checkbox" value="<?php echo $usuarios['usuarioId']; ?>"> <?php echo utf8_encode($usuarios['usuarioNome']); ?><br/>
                                <?php } ?>
                            <?php } else { ?>
                                <?php foreach ($this->usuario as $usuarios) { ?> 
                                    <?php
                                    $usuIds = $usuarios['usuarioId'];
                                    if (in_array($usuIds, $idsFiltrados)) {?>
                                        <input checked type="checkbox" value="<?php echo $usuarios['uusuarioId']; ?>" name="integrantes[]"> <?php echo utf8_encode($usuarios['usuarioNome']); ?>
                                    <?php } else { ?>
                                        <input  type="checkbox" value="<?php echo $usuarios['usuarioId']; ?>" name="integrantes[]"> <?php echo utf8_encode($usuarios['usuarioNome']); ?>
                                    <?php } ?>
                                    <?php
                                    echo '<br/>';
                                }
                            }
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label"></label>
                        <div class="col-sm-6">
                            <input type="submit" class="btn btn-primary" value="Confirmar"/>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>