<?php if (count($this->messages) == 1) { ?>
    <?php foreach ($this->messages as $msg) { ?>
        <div class="alert alert-primary alert-white rounded">
            <div class="icon"><i class="fa fa-check"></i></div>
            <?php echo $msg; ?>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
        
    <?php } ?>
<?php } ?>
<div class="block-flat">
    <div class="header">              
        <h3><i class="fa fa-suitcase"></i> Equipes</h3>
        <div class="text-center">
            <a class="btn btn-primary " href="<?php echo $this->url(array('admin' => 'equipe', 'controller' => 'equipe', 'action' => 'form')); ?>"><i class="fa fa-plus"></i> Nova equipe</a>
        </div>
    </div>

    <div class="content">

        <table class="no-border hover">
            <thead class="no-border">
                <tr>
                    <th>Nome</th>
                    <th class="text-right"></th>
                </tr>
            </thead>

            <tbody class="no-border-y">
                <?php foreach ($this->equipe as $equipes) { ?>
                    <tr>
                        <td>
                            <?php echo $equipes['equipeNome']; ?>
                        </td>
                        <td class="text-right">
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'equipe', 'action' => 'view', 'id' => $equipes['equipeId']), null, true); ?>" class="btn btn-primary">
                                <i class="fa fa-search">
                                </i>
                            </a>
                            
                            <button data-toggle="modal"  data-target="#mod-error" type="button" class="btn btn-danger btn-flat"><i class="fa fa-trash"></i></button>

                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'equipe', 'action' => 'form', 'id' => $equipes['equipeId']), null, true); ?>" class="btn btn-success">
                                <i class="fa fa-edit">
                                </i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="mod-error" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <div class="i-circle danger"><i class="fa fa-times"></i></div>
                    <h4>Atenção!</h4>
                    <p>Deseja realmente excluir esse grupo?</p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Cancel</button>
                <a class="btn btn-default btn-flat" href="<?php
                   echo $this->
                           url(array('module' => 'admin', 'controller' => 'equipe', 'action' => 'drop', 'id' => $equipes['equipeId']), null, true);
                   ?>">
                    Confirmar
                </a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->