<div class="row">
  <div class="col-md-12">
    <div class="block-flat">
      <div class="header">							
        <h3>
          <i class="fa fa-user">            
          </i>
        </h3>
      </div>
      <div class="content">
        <div class="container">
          <div class="row">
            <div class="col-sm-2 col-md-2">
            </div>a
            <div class="col-sm-4 col-md-4">

            </div>
          </div>
          <br/>
          <br/>
          <br/>
          <a  class="btn btn-danger" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario', 'action' => 'index'),null,true);?>">
            Voltar 
          </a>
          <a  class="btn btn-primary" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario', 'action' => 'form', 'id' => $usuario['usuarioId']),null,true);?>">
            Editar 
          </a>
        </div>
      </div>
    </div>				
  </div>
</div>