<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title Page</title>
    <link rel="stylesheet" href="assets/site/css/normalize.css"/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,700,400,600' rel='stylesheet' type='text/css'/>
    <link rel="stylesheet" href="assets/site/css/estilo.css"/>
  </head>
  <body>
    <div id="content">
      <div id="header">
        <img src="assets/site/imgs/logo.png">
        <ul id="menu">
          <li><a href="#">Início</a></li>
          <li><a href="#">Projetos</a></li>
          <li><a href="#">Sobre</a></li>
          <li><a href="#">Blog</a></li>
        </ul>
      </div>

      <div id="slide">
        <img src="http://placehold.it/1349x370"/>
      </div>

      <div id="welcome" class="info container">
        <div class="info-header">
          <h2>
            Noticias!
          </h2>
          <p>
            Lorem ipsum Excepteur consequat Duis qui cupidatat in aliquip Ut minim eiusmod consequat dolore et cupidatat commodo Ut enim et veniam dolor tempor dolor tempor commodo in sed dolor proident veniam incididunt exercitation ut occaecat mollit.
          </p>
        </div>

        <div class="info-item">
          <h3>Fask booking</h3>
          <p>
            Lorem ipsum Excepteur consequat Duis qui cupidatat in aliquip Ut minim eiusmod consequat dolore et cupidatat commodo Ut enim et veniam dolor tempor dolor tempor commodo in sed dolor proident veniam incididunt exercitation ut occaecat mollit.
          </p>
          <a class="button" href="#">MORE</a>
        </div>

        <div class="info-item">
          <h3>Fask booking</h3>
          <p>
            Lorem ipsum Excepteur consequat Duis qui cupidatat in aliquip Ut minim eiusmod consequat dolore et cupidatat commodo Ut enim et veniam dolor tempor dolor tempor commodo in sed dolor proident veniam incididunt exercitation ut occaecat mollit.
          </p>
          <a class="button" href="#">MORE</a>
        </div>

        <div class="info-item">
          <h3>Fask booking</h3>
          <p>
            Lorem ipsum Excepteur consequat Duis qui cupidatat in aliquip Ut minim eiusmod consequat dolore et cupidatat commodo Ut enim et veniam dolor tempor dolor tempor commodo in sed dolor proident veniam incididunt exercitation ut occaecat mollit.
          </p>
          <a class="button" href="#">MORE</a>

        </div>
        <div class="clearfix"></div>
      </div>

      <div id="featured-offers" class="info container">
        <div class="info-header">

        </div>

        <div class="info-item">
          <img src="assets/site/imgs/img01.jpg"/>
        </div>
        <div class="info-item">
          <img src="assets/site/imgs/img02.jpg"/>
        </div>
        <div class="info-item">
          <img src="assets/site/imgs/img03.jpg"/>
        </div>

        <div class="info-item item-3x">
          <a class="button" href="#">MORE</a>
        </div>
        <div class="clearfix"></div>
      </div>

      <div id="footer" class="center">
        <div class="style-contact">
          <b id="teste">
            Taxy Service (c) 2014 | Provacy Policy
          </b>
        </div>
      </div>
    </div>
  </body>
</html>