<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <base href="<?php echo $this->baseUrl('/') ?>">

        <link rel="shortcut icon" href="assets/admin/images/icon.png">

        <title>SIC</title>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,400italic,700,800' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Raleway:300,200,100' rel='stylesheet' type='text/css'>

        <!-- Bootstrap core CSS -->
        <link href="assets/admin/js/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="assets/admin/js/jquery.gritter/css/jquery.gritter.css" />
        <link rel="stylesheet" href="assets/admin/fonts/font-awesome-4/css/font-awesome.min.css">
        <link rel="stylesheet" href="assets/admin/js/jasny.bootstrap/extend/css/jasny-bootstrap.min.css">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="../../assets/js/html5shiv.js"></script>
            <script src="../../assets/js/respond.min.js"></script>
            <![endif]-->
        <link rel="stylesheet" type="text/css" href="assets/admin/js/jquery.nanoscroller/nanoscroller.css" />
        <link href="assets/admin/css/style.css" rel="stylesheet" />
        <script src="http://code.jquery.com/jquery-1.11.1.min.js" type="text/javascript"></script>
    </head>
    <body class="animated">
        <script src="assets/admin/js/jquery.js"></script>
        <script src="assets/admin/js/jquery.cookie/jquery.cookie.js"></script>
        <script src="assets/admin/js/jquery.pushmenu/js/jPushMenu.js"></script>
        <script type="text/javascript" src="assets/admin/js/jquery.nanoscroller/jquery.nanoscroller.js"></script>
        <script type="text/javascript" src="assets/admin/js/jquery.sparkline/jquery.sparkline.min.js"></script>
        <script type="text/javascript" src="assets/admin/js/jquery.ui/jquery-ui.js" ></script>
        <script type="text/javascript" src="assets/admin/js/jquery.gritter/js/jquery.gritter.js"></script>
        <script type="text/javascript" src="assets/admin/js/behaviour/core.js"></script>

        <!-- Bootstrap core JavaScript
            ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="assets/admin/js/bootstrap/dist/js/bootstrap.min.js"></script>

        <div class="block-flat">
            <div class="header text-center">							
                <h3><i class="fa fa-user"></i> Cadastro de Usuários</h3>
            </div>
            <div class="content">
                <form method="post" enctype="multipart/form-data" class="form-horizontal group-border-dashed" action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario', 'action' => 'save'), null, true); ?>" style="border-radius: 0px;">
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Escolha o seu Curso</label>
                        <div class="col-sm-6">
                            <select class="form-control" name="usuarioCursoId">
                                <option>
                                    Selecione o curso
                                </option>
                                <?php foreach ($this->cursoAll as $cursos) { ?>
                                    <option <?php echo $this->usuario['usuarioCursoId'] == $cursos['cursoId'] ? 'selected' : ''; ?> value="<?php echo $cursos['cursoId'] ?>"> 
                                        <?php echo utf8_encode($cursos['cursoNome']); ?>
                                    </option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Nome</label>
                        <div class="col-sm-6">
                            <input type="text"  placeholder="Digite aqui seu nome" class="form-control" name="usuarioNome" value="<?php echo utf8_encode($this->usuario['usuarioNome']); ?>"/>
                        </div>
                    </div>
                    <?php if (empty($this->usuario['usuarioId'])) { ?>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Password</label>
                            <div class="col-sm-3">
                                <input type="password" name="usuarioSenha" placeholder="Digite aqui sua senha" class="form-control">
                            </div>
                            <div class="col-sm-3">
                                <input type="password" name="adm" placeholder="Digite aqui sua senha" class="form-control">
                            </div>
                        </div>
                        <script type="text/javascript">
                            $(document).ready(function () {
                                $('#mod-error').modal('show');
                            });
                        </script>
                    <?php } ?>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Email</label>
                        <div class="col-sm-6">
                            <input type="text" name="usuarioEmail" class="form-control" placeholder="Digite aqui seu E-Mail" value="<?php echo $this->usuario['usuarioEmail']; ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Período</label>
                        <div class="col-sm-2">
                            <select name="usuarioPeriodo" class="form-control">
                                <option>
                                    informe seu período
                                </option>
                                <?php foreach ($this->periodo as $p) { ?>
                                    <option <?php echo $this->usuario['usuarioPeriodo'] == $p ? 'selected' : ''; ?> value="<?php echo $p ?>"> 
                                        <?php echo utf8_encode($p); ?>
                                    </option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="col-sm-4">
                            <input class="form-control" name="usuarioFone" placeholder="Digite aqui seu telefone" value="<?php echo $this->usuario['usuarioFone']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Login</label>
                        <div class="col-sm-3">
                            <input type="text" name="usuarioLogin" class="form-control" value="<?php echo $this->usuario['usuarioLogin']; ?>" placeholder="Digite aqui seu login">
                        </div>
                        <div class="col-sm-3">
                            <input type="text" name="usuarioStatus" class="form-control" value="<?php echo $this->usuario['usuarioStatus']; ?>" placeholder="Defina o Status">
                        </div>
                    </div>

                    <?php if ($this->usuario['usuarioId'] != null) { ?>
                        <input type="hidden" name="usuarioId" class="form-control" value="<?php echo $this->usuario['usuarioId']; ?>">
                    <?php } ?>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Selecione a Imagem</label>
                        <div class="col-sm-6">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-new thumbnail" style="height: 150px;">
                                    <img src="<?php echo!empty($this->usuario['usuarioFotoCaminho']) ? 'imagens/' . $this->usuario['usuarioFotoCaminho'] : 'http://placehold.it/190x140/7761A7/ffffff' ?>" alt="...">
                                </div>
                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                                <div>
                                    <span class="btn btn-primary btn-file"><span class="fileinput-new">Selecione</span><span class="fileinput-exists">Change</span><input type="file" name="usuarioFotoCaminho" value="<?php echo empty($this->usuario['usuarioFotoCaminho'] ? '' : $this->usuario['usuarioFotoCaminho  '] ); ?>"></span>
                                    <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label">Grupos</label>
                        <div class="col-sm-3">
                            <?php foreach ($this->grupos as $g) { ?>
                                <?php $idG = $g['grupoId']; ?>
                                <?php if (!empty($this->usuario['usuarioId']) && in_array($idG, $this->usuarioGrupoAll)) { ?>
                                    <input value="<?php echo $idG;?>" name="integrantes[]" checked type="checkbox"> <?php echo utf8_encode($g['grupoNome']); ?> <br/>
                                <?php } else { ?>
                                    <input value="<?php echo $idG;?>" name="integrantes[]" type="checkbox"> <?php echo utf8_encode($g['grupoNome']); ?> <br/>
                                <?php } ?>
                            <?php } ?>


                            <div class="col-sm-3">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"></label>
                            <div class="col-sm-6">
                                <input type="submit" class="btn btn-success" value="Confirmar">
                                <a class="btn btn-primary" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario'), null, true); ?>"> Voltar</a>
                            </div>
                        </div>
                </form>
            </div>
        </div>

        <div class="modal fade" id="mod-error" tabindex="-1" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="text-center">
                            <div class="i-circle primary"><i class="fa fa-info"></i></div>
                            <h4>Atenção!</h4>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

                            </p>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-default btn-flat" href="">
                            Confirmar
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript" src="assets/admin/js/jasny.bootstrap/extend/js/jasny-bootstrap.min.js">
                            < script type = "text/javascript" src = "assets/admin/js/jquery.upload/js/jquery.fileupload.js" ></script>
        <script type="text/javascript" src="assets/admin/js/jquery.upload/js/"></script>
        <script type="text/javascript" src="assets/admin/js/jquery.upload/js/jquery.iframe-transport.js"></script>
        <script type="text/javascript" src="assets/admin/js/jquery.flot/jquery.flot.js"></script>
        <script type="text/javascript" src="assets/admin/js/jquery.flot/jquery.flot.pie.js"></script>
        <script type="text/javascript" src="assets/admin/js/jquery.flot/jquery.flot.resize.js"></script>
        <script type="text/javascript" src="assets/admin/js/jquery.flot/jquery.flot.labels.js"></script>
    </body>
</html>




