<?php if (count($this->messages) == 1) { ?>
    <?php foreach ($this->messages as $msg) { ?>
        <div class="alert alert-primary alert-white rounded">
            <div class="icon"><i class="fa fa-check"></i></div>
            <?php echo $msg; ?>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>

    <?php } ?>
<?php } ?>
<div class="block-flat">
    <div class="header">              
        <h4>
            <i class="fa fa-user">
            </i>
            &nbsp;&nbsp; Usuários
        </h4>
        <div class="text-center">
            <a class="btn btn-trans btn-primary"  href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario', 'action' => 'form'), null, true); ?>">
                <i class="fa fa-plus"></i>
                Novo usuário
            </a>
        </div>
    </div>
    <div class="content">
        <?php
        if (empty($this->usuario)) {
            echo 'Não existem usuarios cadastrados no sistema';
        } else {
            ?>
            <table class="no-border hover">
                <thead class="no-border">
                    <tr>
                        <th class="text-left">Nome</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Curso</th>
                        <th class="text-right"></th>
                    </tr>
                </thead>

                <tbody class="no-border-y">
                    <?php
                    foreach ($this->usuario as $value) {
                        ?>  
                        <tr>
                            <td class="text-left">
                                <?php echo utf8_encode($value['usuarioNome']); ?>
                            </td>
                            <td>
                                <?php echo utf8_encode($value['usuarioEmail']); ?>
                            </td>
                            <td>
                                <?php echo $value['usuarioStatus'] == 1 ? 'Atívo' : 'Inatívo'; ?>
                            </td>
                            <td>
                                <?php echo utf8_encode($value['cursoNome']); ?>
                            </td>
                            <td class="text-right">
                                <a class="btn btn-primary" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario', 'action' => 'view', 'id' => $value["usuarioId"]), null, true); ?>">
                                    <i class="fa fa-search">
                                    </i>
                                </a>   
                                
                                <button data-toggle="modal"  data-target="#mod-error" type="button" class="btn btn-danger btn-flat"><i class="fa fa-trash"></i></button>
                                
                                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario', 'action' => 'form', 'id' => $value['usuarioId']), null, true); ?>" class="btn btn-success">
                                    <i class="fa fa-edit">    
                                    </i>
                                </a>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
            </table>
        <?php } ?>            
    </div>
</div>
<div class="modal fade" id="mod-error" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <div class="i-circle danger"><i class="fa fa-times"></i></div>
                    <h4>Atenção!</h4>
                    <p>Deseja realmente excluir esse usuário?</p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Cancel</button>
                <a class="btn btn-default btn-flat" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario', 'action' => 'drop', 'id' => $value['usuarioId']), null, true); ?>">        
                    Confirmar
                </a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->