<div class="block-flat">
  <div class="header">              
    <h3>Cadastro de Usuários</h3>
  </div>
  <div class="content">
    <table class="no-border hover">
      <thead class="no-border">
        <tr>
          <th class="text-left">Nome</th>
          <th>Email</th>
          <th>Status</th>
          <th class="text-right"></th>
        </tr>
      </thead>
      
      <tbody class="no-border-y">
        <?php
        foreach ($this->usuario as $value) {
        ?>  
        <tr>
          <td class="text-left">
            <?php echo utf8_encode($value['usuarioNome']); ?>
          </td>
          <td>
            <?php echo utf8_encode($value['usuarioEmail']); ?>
          </td>
          <td>
            <?php echo utf8_encode($value['usuarioStatus']); ?>
          </td>
          <td class="text-right">
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario', 'action' => 'view', 'id' => $value["usuarioId"]),null,true);?>" class="btn btn-primary">
              <i class="fa fa-search">
              </i>
            </a>


            <a class="btn btn-danger" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario', 'action' => 'drop', 'id' => $value['usuarioId']), null, true); ?>">
              <i class="fa fa-trash">
              </i>
            </a>


            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario', 'action' => 'form', 'id' => $value['usuarioId']), null, true); ?>" class="btn btn-success">
              <i class="fa fa-edit">    
              </i>
            </a>
          </td>
        </tr>
        <?php  
        }
        ?>
      </tbody>
    </table>            
  </div>
</div>